#!/usr/bin/env python
#
# Very simple wrapper to go in /usr/bin to be executed by init script. 
#
from vc3.master import VC3MasterCLI

def main():
    '''
    Simplest possible invocation of Infoservice program. Does not have the .py extension
    to keep the RPM building system happy. 
    '''
    srv = VC3MasterCLI()
    srv.run()
        
if __name__ == "__main__":
    main()
